# Generated by Django 5.0 on 2024-02-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_locations_userprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='company_id',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='base.company'),
        ),
    ]
