# Generated by Django 5.0 on 2024-02-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_user_company_company_id_company_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='user',
        ),
    ]
