# Generated by Django 5.0 on 2024-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_job_post_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
