# Generated by Django 5.0 on 2024-02-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_job_post_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
