# Generated by Django 5.0 on 2024-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_job_post_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
